#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Nov 25 22:47:19 HKT 2024
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 26c0ecfe074347ed8f89c1678ff23840 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot sim_top_tb_behav xil_defaultlib.sim_top_tb -log elaborate.log"
xelab -wto 26c0ecfe074347ed8f89c1678ff23840 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot sim_top_tb_behav xil_defaultlib.sim_top_tb -log elaborate.log

